name: Deploy TiddlyWiki to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: write


concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  release-and-page:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: oeyoews/tiddlywiki-publish@main
        with:
          site-title: " My Personal notes"
          favicon: "./favicon.svg"
          tiddlers-directory: .
          default-home-tiddlers: 最近更新
          version: "master"
